[package]
name = "serde_many_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", default-features = false, features = ["derive", "visit-mut", "parsing", "proc-macro"] }
quote = "1.0"
proc-macro2 = "1.0.89"
serde_derive_internals = "0.29"
